// <auto-generated />
using System;
using BikeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeShop.Data.Migrations
{
    [DbContext(typeof(BikeShopContext))]
    partial class BikeShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeShop.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Dries",
                            Name = "Yperman"
                        });
                });

            modelBuilder.Entity("BikeShop.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Specialized",
                            Price = 2048m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Specialized",
                            Price = 511m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pinarello",
                            Price = 1581m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Trek",
                            Price = 1965m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Specialized",
                            Price = 3993m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Specialized",
                            Price = 4620m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cannondale",
                            Price = 4782m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cervelo",
                            Price = 2286m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Scott",
                            Price = 3307m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Giant",
                            Price = 1063m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Giant",
                            Price = 3736m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pinarello",
                            Price = 668m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Specialized",
                            Price = 3285m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Specialized",
                            Price = 4368m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Giant",
                            Price = 3487m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cannondale",
                            Price = 3651m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bianchi",
                            Price = 3477m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Specialized",
                            Price = 2441m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cervelo",
                            Price = 1306m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Specialized",
                            Price = 4584m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bianchi",
                            Price = 663m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Trek",
                            Price = 2172m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Pinarello",
                            Price = 712m
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bianchi",
                            Price = 2856m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Trek",
                            Price = 1815m
                        },
                        new
                        {
                            Id = 26,
                            Name = "Scott",
                            Price = 3329m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Scott",
                            Price = 1940m
                        },
                        new
                        {
                            Id = 28,
                            Name = "Giant",
                            Price = 4621m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Trek",
                            Price = 3154m
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cannondale",
                            Price = 4361m
                        },
                        new
                        {
                            Id = 31,
                            Name = "Scott",
                            Price = 2832m
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cervelo",
                            Price = 1360m
                        },
                        new
                        {
                            Id = 33,
                            Name = "Bianchi",
                            Price = 3795m
                        },
                        new
                        {
                            Id = 34,
                            Name = "Scott",
                            Price = 4703m
                        },
                        new
                        {
                            Id = 35,
                            Name = "Trek",
                            Price = 739m
                        },
                        new
                        {
                            Id = 36,
                            Name = "Giant",
                            Price = 3272m
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cervelo",
                            Price = 3416m
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cannondale",
                            Price = 4057m
                        },
                        new
                        {
                            Id = 39,
                            Name = "Trek",
                            Price = 1855m
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cervelo",
                            Price = 3267m
                        },
                        new
                        {
                            Id = 41,
                            Name = "Giant",
                            Price = 4815m
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cervelo",
                            Price = 2182m
                        },
                        new
                        {
                            Id = 43,
                            Name = "Specialized",
                            Price = 1880m
                        },
                        new
                        {
                            Id = 44,
                            Name = "Pinarello",
                            Price = 3190m
                        },
                        new
                        {
                            Id = 45,
                            Name = "Scott",
                            Price = 1832m
                        },
                        new
                        {
                            Id = 46,
                            Name = "Trek",
                            Price = 4424m
                        },
                        new
                        {
                            Id = 47,
                            Name = "Scott",
                            Price = 733m
                        },
                        new
                        {
                            Id = 48,
                            Name = "Giant",
                            Price = 1574m
                        },
                        new
                        {
                            Id = 49,
                            Name = "Trek",
                            Price = 1611m
                        },
                        new
                        {
                            Id = 50,
                            Name = "Bianchi",
                            Price = 4371m
                        });
                });

            modelBuilder.Entity("BikeShop.Data.Entities.ShoppingBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("shoppingBags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Date = new DateTime(2023, 3, 22, 19, 10, 52, 145, DateTimeKind.Local).AddTicks(759)
                        });
                });

            modelBuilder.Entity("BikeShop.Data.Entities.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingBagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingBagId");

                    b.ToTable("shoppingItems");
                });

            modelBuilder.Entity("BikeShop.Data.Entities.ShoppingBag", b =>
                {
                    b.HasOne("BikeShop.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BikeShop.Data.Entities.ShoppingItem", b =>
                {
                    b.HasOne("BikeShop.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeShop.Data.Entities.ShoppingBag", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingBagId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BikeShop.Data.Entities.ShoppingBag", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
